"""Strict data contracts shared by the M1 API, services, tools, and frontend."""

from app.schemas.auth import CurrentUser, LoginRequest, LoginResponse
from app.schemas.chat import (
    ChatMessageRequest,
    ChatSuccessResponse,
    CreateThreadRequest,
    ExecutionSummary,
    ThreadResponse,
)
from app.schemas.common import (
    ApiErrorResponse,
    ErrorDetail,
    M1Schema,
    ToolEnvelope,
    ToolMeta,
)
from app.schemas.context import (
    CitationValidationResult,
    ContextBundle,
    ContextCitation,
    ContextSegment,
)
from app.schemas.evidence import (
    DocumentEvidenceDetail,
    DocumentEvidenceSummary,
    EvidenceDetail,
    EvidenceSummary,
)
from app.schemas.files import (
    FileListResponse,
    FileRegistrationInput,
    FileResponse,
    FileStateUpdate,
    FileUploadResponse,
)
from app.schemas.inventory import (
    InventoryIntent,
    InventoryResult,
    SearchInventoryInput,
)
from app.schemas.knowledge import (
    DocumentAclGrantInput,
    DocumentAclResponse,
    DocumentChunkSetPublication,
    DocumentCreateInput,
    DocumentDetailResponse,
    DocumentIndexResponse,
    DocumentIndexStateUpdate,
    DocumentParseStateUpdate,
    DocumentResponse,
    DocumentVersionCreateInput,
    DocumentVersionResponse,
)
from app.schemas.product import (
    GetProductSpecInput,
    ProductSpecItem,
    ProductSpecResult,
)
from app.schemas.retrieval import (
    CsvRetrievalSourceLocator,
    DenseRetrievalScore,
    DocxRetrievalSourceLocator,
    LexicalRetrievalScore,
    PdfRetrievalSourceLocator,
    RetrievalCandidateIdentity,
    RetrievalDocumentMetadata,
    RetrievalEmbeddingIdentity,
    RetrievalFtsIdentity,
    RetrievalRequest,
    RetrievalResponse,
    RetrievalResult,
    RetrievalScoreBreakdown,
    XlsxRetrievalSourceLocator,
)

__all__ = [
    "ApiErrorResponse",
    "ChatMessageRequest",
    "ChatSuccessResponse",
    "CitationValidationResult",
    "ContextBundle",
    "ContextCitation",
    "ContextSegment",
    "CreateThreadRequest",
    "CsvRetrievalSourceLocator",
    "CurrentUser",
    "DenseRetrievalScore",
    "DocumentAclGrantInput",
    "DocumentAclResponse",
    "DocumentChunkSetPublication",
    "DocumentCreateInput",
    "DocumentDetailResponse",
    "DocumentEvidenceDetail",
    "DocumentEvidenceSummary",
    "DocumentIndexResponse",
    "DocumentIndexStateUpdate",
    "DocumentParseStateUpdate",
    "DocumentResponse",
    "DocumentVersionCreateInput",
    "DocumentVersionResponse",
    "DocxRetrievalSourceLocator",
    "ErrorDetail",
    "EvidenceDetail",
    "EvidenceSummary",
    "ExecutionSummary",
    "FileListResponse",
    "FileRegistrationInput",
    "FileResponse",
    "FileStateUpdate",
    "FileUploadResponse",
    "GetProductSpecInput",
    "InventoryIntent",
    "InventoryResult",
    "LexicalRetrievalScore",
    "LoginRequest",
    "LoginResponse",
    "M1Schema",
    "PdfRetrievalSourceLocator",
    "ProductSpecItem",
    "ProductSpecResult",
    "RetrievalCandidateIdentity",
    "RetrievalDocumentMetadata",
    "RetrievalEmbeddingIdentity",
    "RetrievalFtsIdentity",
    "RetrievalRequest",
    "RetrievalResponse",
    "RetrievalResult",
    "RetrievalScoreBreakdown",
    "SearchInventoryInput",
    "ThreadResponse",
    "ToolEnvelope",
    "ToolMeta",
    "XlsxRetrievalSourceLocator",
]
